export const CHANNEL_LIST_ITEM_CREATE = 'CHANNEL_LIST_ITEM_CREATE';
export const CHANNEL_LIST_ITEM_UPDATE = 'CHANNEL_LIST_ITEM_UPDATE';
export const CHANNEL_LIST_ITEM_DELETE = 'CHANNEL_LIST_ITEM_DELETE';
export const CHANNEL_LIST_ITEM_START_EDITING = 'CHANNEL_LIST_ITEM_START_EDITING';
export const CHANNEL_LIST_ITEM_CANCEL_EDITING = 'CHANNEL_LIST_ITEM_CANCEL_EDITING';
export const CHANNEL_LIST_ITEM_START_CREATING = 'CHANNEL_LIST_ITEM_START_CREATING';
export const CHANNEL_LIST_ITEM_CANCEL_CREATING = 'CHANNEL_LIST_ITEM_CANCEL_CREATING';
export const CHANNEL_LIST_SAVING_STARTED = 'CHANNEL_LIST_SAVING_STARTED';
export const CHANNEL_LIST_SAVING_FINISHED = 'CHANNEL_LIST_SAVING_FINISHED';

export const SHARED_RECEIVE_TOKEN = 'SHARED_RECEIVE_TOKEN';
export const SHARED_INVALIDATE_TOKEN = 'SHARED_INVALIDATE_TOKEN';
export const SHARED_AUTHENTICATION_FAILED = 'SHARED_AUTHENTICATION_FAILED';
export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_DISMISS_ERROR = 'SHARED_DISMISS_ERROR';

export const PROFILE_FETCHING_STARTED = 'PROFILE_FETCHING_STARTED';
export const PROFILE_FETCHING_FAILED = 'PROFILE_FETCHING_FAILED';
export const PROFILE_UPDATE_DETAILS = 'PROFILE_UPDATE_DETAILS';
export const PROFILE_UPDATE_AVATAR = 'PROFILE_UPDATE_AVATAR';
export const PROFILE_UPLOADING_FAILED = 'PROFILE_UPLOADING_FAILED';
export const PROFILE_AVATAR_UPLOADING_STARTED = 'PROFILE_AVATAR_UPLOADING_STARTED';
export const PROFILE_AVATAR_UPLOADING_FAILED = 'PROFILE_AVATAR_UPLOADING_FAILED';
export const PROFILE_AVATAR_FETCHING_STARTED = 'PROFILE_AVATAR_FETCHING_STARTED';
export const PROFILE_AVATAR_FETCHING_FAILED = 'PROFILE_AVATAR_FETCHING_FAILED';