export const CHANNELS_LOAD_ALL = 'CHANNELS_LOAD_ALL';
export const CHANNEL_LIST_ITEM_CREATE = 'CHANNEL_LIST_ITEM_CREATE';
export const CHANNEL_LIST_ITEM_UPDATE = 'CHANNEL_LIST_ITEM_UPDATE';
export const CHANNEL_LIST_ITEM_DELETE = 'CHANNEL_LIST_ITEM_DELETE';
export const CHANNEL_LIST_ITEM_START_EDITING = 'CHANNEL_LIST_ITEM_START_EDITING';
export const CHANNEL_LIST_ITEM_CANCEL_EDITING = 'CHANNEL_LIST_ITEM_CANCEL_EDITING';
export const CHANNEL_LIST_ITEM_START_CREATING = 'CHANNEL_LIST_ITEM_START_CREATING';
export const CHANNEL_LIST_ITEM_CANCEL_CREATING = 'CHANNEL_LIST_ITEM_CANCEL_CREATING';
export const CHANNEL_LIST_SAVING_STARTED = 'CHANNEL_LIST_SAVING_STARTED';
export const CHANNEL_LIST_SAVING_FINISHED = 'CHANNEL_LIST_SAVING_FINISHED';

export const SHARED_RECEIVE_TOKEN = 'SHARED_RECEIVE_TOKEN';
export const SHARED_RECEIVE_EMAIL = 'SHARED_RECEIVE_EMAIL';
export const SHARED_INVALIDATE_TOKEN = 'SHARED_INVALIDATE_TOKEN';
export const SHARED_AUTHENTICATION_FAILED = 'SHARED_AUTHENTICATION_FAILED';
export const SHARED_AUTHENTICATION_STARTED = 'SHARED_AUTHENTICATION_STARTED';
export const SHARED_DISMISS_STATUS_MESSAGE = 'SHARED_DISMISS_STATUS_MESSAGE';
export const SHARED_LOAD_USERS = 'SHARED_LOAD_USERS';
export const SHARED_USERS_FETCHING_FAILED = 'SHARED_USERS_FETCHING_FAILED';

export const PROFILE_DETAILS_FETCHING_STARTED = 'PROFILE_DETAILS_FETCHING_STARTED';
export const PROFILE_DETAILS_UPLOADING_SUCCESS = 'PROFILE_DETAILS_UPLOADING_SUCCESS';
export const PROFILE_DETAILS_FETCHING_FAILED = 'PROFILE_DETAILS_FETCHING_FAILED';
export const PROFILE_UPDATE_DETAILS = 'PROFILE_UPDATE_DETAILS';
export const PROFILE_UPDATE_AVATAR = 'PROFILE_UPDATE_AVATAR';
export const PROFILE_DETAILS_UPLOADING_FAILED = 'PROFILE_DETAILS_UPLOADING_FAILED';
export const PROFILE_AVATAR_UPLOADING_STARTED = 'PROFILE_AVATAR_UPLOADING_STARTED';
export const PROFILE_AVATAR_UPLOADING_FAILED = 'PROFILE_AVATAR_UPLOADING_FAILED';
export const PROFILE_AVATAR_FETCHING_STARTED = 'PROFILE_AVATAR_FETCHING_STARTED';
export const PROFILE_AVATAR_FETCHING_FAILED = 'PROFILE_AVATAR_FETCHING_FAILED';
export const PROFILE_AVATAR_UPLOADING_SUCCESS = 'PROFILE_AVATAR_UPLOADING_SUCCESS';

export const CHANNEL_UPLOADING_FAILED = 'CHANNEL_UPLOADING_FAILED';
export const CHANNEL_DELETING_FAILED = 'CHANNEL_DELETING_FAILED';
export const CHANNEL_DELETING_SUCCESS = 'CHANNEL_DELETING_SUCCESS';
export const CHANNELS_FETCHING_FAILED = 'CHANNELS_FETCHING_FAILED';

export const LOGIN_UPDATE_EMAIL = 'LOGIN_UPDATE_EMAIL';

export const MESSAGE_LOAD_ALL = 'MESSAGE_LOAD_ALL';
export const MESSAGES_FETCHING_STARTED = 'MESSAGES_FETCHING_STARTED';
export const MESSAGES_FETCHING_FAILED = 'MESSAGES_FETCHING_FAILED';
export const MESSAGE_DELETING_STARTED = 'MESSAGE_DELETING_STARTED';
export const MESSAGE_DELETING_FAILED = 'MESSAGE_DELETING_FAILED';
export const MESSAGE_DELETING_SUCCESS = 'MESSAGE_DELETING_SUCCESS';
export const MESSAGE_UPDATING_STARTED = 'MESSAGE_UPDATING_STARTED';
export const MESSAGE_UPDATING_SUCCESS = 'MESSAGE_UPDATING_SUCCESS';
export const MESSAGE_UPDATING_FAILED = 'MESSAGE_UPDATING_FAILED';
export const MESSAGE_UPDATE_AVATAR = 'MESSAGE_UPDATE_AVATAR';
export const MESSAGE_LIST_ITEM_CREATE = 'MESSAGE_LIST_ITEM_CREATE';
export const MESSAGE_LIST_ITEM_UPDATE = 'MESSAGE_LIST_ITEM_UPDATE';
export const MESSAGE_LIST_ITEM_DELETE = 'MESSAGE_LIST_ITEM_DELETE';
export const MESSAGE_UPLOADING_STARTED = 'MESSAGE_UPLOADING_STARTED';
export const MESSAGE_UPLOADING_FAILED = 'MESSAGE_UPLOADING_FAILED';
export const MESSAGE_UPLOADING_SUCCESS = 'MESSAGE_UPLOADING_SUCCESS';
export const MESSGE_FETCHING_AVATAR_FAILED = 'MESSGE_FETCHING_AVATAR_FAILED';