export const CHANNEL_LIST_ITEM_CREATE = 'CHANNEL_LIST_ITEM_CREATE';
export const CHANNEL_LIST_ITEM_UPDATE = 'CHANNEL_LIST_ITEM_UPDATE';
export const CHANNEL_LIST_ITEM_DELETE = 'CHANNEL_LIST_ITEM_DELETE';
export const CHANNEL_LIST_ITEM_START_EDITING = 'CHANNEL_LIST_ITEM_START_EDITING';
export const CHANNEL_LIST_ITEM_CANCEL_EDITING = 'CHANNEL_LIST_ITEM_CANCEL_EDITING';
export const CHANNEL_LIST_ITEM_START_CREATING = 'CHANNEL_LIST_ITEM_START_CREATING';
export const CHANNEL_LIST_ITEM_CANCEL_CREATING = 'CHANNEL_LIST_ITEM_CANCEL_CREATING';
export const CHANNEL_LIST_SAVING_STARTED = 'CHANNEL_LIST_SAVING_STARTED';
export const CHANNEL_LIST_SAVING_FINISHED = 'CHANNEL_LIST_SAVING_FINISHED';

export const SHARED_RECEIVE_TOKEN = 'SHARED_RECEIVE_TOKEN';
export const SHARED_INVALIDATE_TOKEN = 'SHARED_INVALIDATE_TOKEN';